apiVersion: v1
kind: ConfigMap
metadata:
  name: ejbca-config
data:
  config.yaml: |+
    useEST: {{ .Values.ejbca.useEST }}
    defaultESTAlias: {{ .Values.ejbca.useEST }}
    defaultCertificateProfileName: {{ .Values.ejbca.defaultCertificateProfileName }}
    defaultEndEntityProfileName: {{ .Values.ejbca.defaultEndEntityProfileName }}
    defaultCertificateAuthorityName: {{ .Values.ejbca.defaultCertificateAuthorityName }}
    healthcheckPort: {{ .Values.ejbca.healthcheckPort }}
    chainDepth: {{ .Values.ejbca.chainDepth}}